name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checks here
        id: checks
        uses: marcellodesales/checkout@main

      - name: outputs here
        run: |
          echo ${{steps.checks.outputs.a}} and B=${{steps.checks.outputs.b}}
